
name : Bash Script Workflow

on:
  push:
    branches:
      - main
      - '/*'

jobs:
  run-bash-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Bash script syntax check
        run: |
          if bash -n bashscript/version4.sh; then
            echo "No Syntax Error"
          else
            echo "Syntax Error"
            exit 1
          fi
      
      - name : check folder structure
        run: |
          sudo apt-get update && sudo apt-get install -y tree


      - name: Display Folder structure
        run: tree -L 2


